DS-Payring/back-end

src/main/java/com/backend/payring/PayringApplication.java
src/main/java/com/backend/payring/entity/AccountEntity.java
src/main/java/com/backend/payring/entity/BaseEntity.java
src/main/java/com/backend/payring/entity/PaymentEntity.java
src/main/java/com/backend/payring/entity/RoomEntity.java
src/main/java/com/backend/payring/entity/TeamMemberEntity.java
src/main/java/com/backend/payring/entity/TempEntity.java
src/main/java/com/backend/payring/entity/TransferEntity.java
src/main/java/com/backend/payring/entity/UserEntity.java
src/main/java/com/backend/payring/entity/enums/RoomStatus.java

closed #1  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 엔터티 생성 및 관계 설정
N/A

🗃️ Feature: 엔터티 생성 및 관계 설정

---

build.gradle
src/main/java/com/backend/payring/code/ErrorCode.java
src/main/java/com/backend/payring/code/ResponseCode.java
src/main/java/com/backend/payring/config/S3Config.java
src/main/java/com/backend/payring/config/SecurityConfig.java
src/main/java/com/backend/payring/controller/PaymentController.java
src/main/java/com/backend/payring/controller/TempController.java
src/main/java/com/backend/payring/converter/PaymentConverter.java
src/main/java/com/backend/payring/dto/payment/PaymentCreateDTO.java
src/main/java/com/backend/payring/entity/PaymentEntity.java
src/main/java/com/backend/payring/entity/RoomEntity.java
src/main/java/com/backend/payring/exception/RoomException.java
src/main/java/com/backend/payring/exception/UserException.java
src/main/java/com/backend/payring/repository/PaymentRepository.java
src/main/java/com/backend/payring/repository/RoomRepository.java
src/main/java/com/backend/payring/repository/UserRepository.java
src/main/java/com/backend/payring/service/PaymentService.java
src/main/java/com/backend/payring/service/PaymentServiceImpl.java
src/main/java/com/backend/payring/service/S3Uploader.java
src/main/java/com/backend/payring/util/MultipartJackson2HttpMessageConverter.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- s3 연결 및 송금 생성 API 작성 
- N/A

✨ Feature: s3 연결 및 송금 생성 API 작성 

---

src/main/java/com/backend/payring/code/ErrorCode.java
src/main/java/com/backend/payring/code/ResponseCode.java
src/main/java/com/backend/payring/controller/PaymentController.java
src/main/java/com/backend/payring/converter/PaymentConverter.java
src/main/java/com/backend/payring/dto/payment/GetPaymentDTO.java
src/main/java/com/backend/payring/dto/response/ErrorResponseDTO.java
src/main/java/com/backend/payring/exception/GlobalException.java
src/main/java/com/backend/payring/exception/GlobalExceptionHandler.java
src/main/java/com/backend/payring/exception/PaymentException.java
src/main/java/com/backend/payring/repository/PaymentRepository.java
src/main/java/com/backend/payring/service/PaymentService.java
src/main/java/com/backend/payring/service/PaymentServiceImpl.java

closed #5  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- payment CRUD
- 전역 에러 핸들러 설정 
- N/A

✨ Feature: payment CRUD

---

src/main/java/com/backend/payring/code/ErrorCode.java
src/main/java/com/backend/payring/code/ResponseCode.java
src/main/java/com/backend/payring/controller/PaymentController.java
src/main/java/com/backend/payring/controller/TransferController.java
src/main/java/com/backend/payring/converter/TransferConverter.java
src/main/java/com/backend/payring/converter/UserConverter.java
src/main/java/com/backend/payring/dto/payment/PaymentCreateDTO.java
src/main/java/com/backend/payring/dto/transfer/CompleteUserDTO.java
src/main/java/com/backend/payring/dto/transfer/CompletedUserDTO.java
src/main/java/com/backend/payring/dto/transfer/ReceiveDTO.java
src/main/java/com/backend/payring/dto/transfer/ReceiverDTO.java
src/main/java/com/backend/payring/dto/transfer/SendDTO.java
src/main/java/com/backend/payring/dto/transfer/UnCompletedUserDTO.java
src/main/java/com/backend/payring/dto/transfer/UserTransferStatusDTO.java
src/main/java/com/backend/payring/dto/transfer/VerifyTransferDTO.java
src/main/java/com/backend/payring/entity/PaymentEntity.java
src/main/java/com/backend/payring/entity/RoomEntity.java
src/main/java/com/backend/payring/entity/TransferEntity.java
src/main/java/com/backend/payring/entity/UserEntity.java
src/main/java/com/backend/payring/entity/enums/RoomStatus.java
src/main/java/com/backend/payring/exception/TransferException.java
src/main/java/com/backend/payring/repository/AccountRepository.java
src/main/java/com/backend/payring/repository/PaymentRepository.java
src/main/java/com/backend/payring/repository/TeamMemberRepository.java
src/main/java/com/backend/payring/repository/TransferRepository.java
src/main/java/com/backend/payring/repository/UserRepository.java
src/main/java/com/backend/payring/service/PaymentService.java
src/main/java/com/backend/payring/service/PaymentServiceImpl.java
src/main/java/com/backend/payring/service/TransferService.java
src/main/java/com/backend/payring/service/TransferServiceImpl.java

closed #7 : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 송금 관련 API 개발 
N/A

✨ Feature: 송금 관련 API 개발 

---

src/main/java/com/backend/payring/code/ErrorCode.java
src/main/java/com/backend/payring/code/ResponseCode.java
src/main/java/com/backend/payring/controller/PaymentController.java
src/main/java/com/backend/payring/controller/RoomController.java
src/main/java/com/backend/payring/controller/TransferController.java
src/main/java/com/backend/payring/converter/RoomConverter.java
src/main/java/com/backend/payring/dto/payment/PaymentCreateDTO.java
src/main/java/com/backend/payring/dto/room/DurationStatusDTO.java
src/main/java/com/backend/payring/entity/RoomEntity.java
src/main/java/com/backend/payring/repository/RoomRepository.java
src/main/java/com/backend/payring/repository/TeamMemberRepository.java
src/main/java/com/backend/payring/repository/TransferRepository.java
src/main/java/com/backend/payring/service/PaymentServiceImpl.java
src/main/java/com/backend/payring/service/RoomService.java
src/main/java/com/backend/payring/service/RoomServiceImpl.java
src/main/java/com/backend/payring/service/TransferService.java
src/main/java/com/backend/payring/service/TransferServiceImpl.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 기간별 방별 정산 현황 조회 API 작성
N/A

✨ 기간별 방별 정산 현황 조회 API 작성

---

src/main/java/com/backend/payring/controller/PaymentController.java

closed #10  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 방 정산 POST 요청으로 변경
N/A

🔨 Refactor: 방 정산 POST 요청으로 변경

---

.gitignore
build.gradle
src/main/java/com/backend/payring/code/ErrorCode.java
src/main/java/com/backend/payring/controller/PaymentController.java
src/main/java/com/backend/payring/service/PaymentServiceImpl.java
src/main/java/com/backend/payring/service/RoomServiceImpl.java
src/main/java/com/backend/payring/service/TransferServiceImpl.java
src/main/java/com/backend/payring/service/ocr/GoogleCloudVisionService.java
src/main/java/com/backend/payring/service/s3/S3Uploader.java

closed #13  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
-  OCR을 사용해서 송금 인증 기능 구현
N/A

✨ Feature: OCR을 사용해서 송금 인증 기능 구현

---

src/main/java/com/backend/payring/code/ErrorCode.java
src/main/java/com/backend/payring/config/SecurityConfig.java
src/main/java/com/backend/payring/controller/UserController.java
src/main/java/com/backend/payring/converter/UserConverter.java
src/main/java/com/backend/payring/exception/UserException.java
src/main/java/com/backend/payring/repository/UserRepository.java
src/main/java/com/backend/payring/security/JWTAuthenticationFilter.java
src/main/java/com/backend/payring/service/JWTServiceImpl.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

🔨 Refactor: 이메일 대신 userId 토큰 저장으로 수정

---

.github/workflows/develop.yml

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- application.yml 경로 수정, google-vision-key.json 추가
N/A

🐛 Fix: application.yml 경로 수정, google-vision-key.json 추가

---

src/main/java/com/backend/payring/controller/HealthCheckController.java

closed #18  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

✨ Feature: heathcheck url 추가

---

.github/workflows/develop.yml
src/main/java/com/backend/payring/service/EmailServiceImpl.java
src/main/resources/templates/code.html

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

✨ Feature: 인증코드 메일 html 템플릿 적용

---

build.gradle

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

➕ Chore: tjymeleaf, mail 의존성 추가

---

src/main/java/com/backend/payring/controller/UserController.java
src/main/java/com/backend/payring/service/UserServiceImpl.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

🐛 Fix: 예외 throw문 추가

---

src/main/java/com/backend/payring/service/UserServiceImpl.java

[//]: #26 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 이메일 인증 중복 확인 로직 수정
- 회원 가입 중복 확인 로직 수정
N/A

🐛 Fix: 이메일 중복 로직 수정

---

src/main/java/com/backend/payring/code/ResponseCode.java
src/main/java/com/backend/payring/config/SecurityConfig.java
src/main/java/com/backend/payring/controller/HealthCheckController.java
src/main/java/com/backend/payring/controller/UserController.java
src/main/java/com/backend/payring/dto/user/CustomUserDetails.java
src/main/java/com/backend/payring/jwt/JWTFilter.java
src/main/java/com/backend/payring/jwt/JWTUtil.java
src/main/java/com/backend/payring/jwt/LoginFilter.java
src/main/java/com/backend/payring/service/UserServiceImpl.java
src/main/java/com/backend/payring/util/TokenErrorResponse.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

🔨 Refactor: 회원가입, 로그인 로직 전체 수정

---

src/main/java/com/backend/payring/controller/UserController.java
src/main/java/com/backend/payring/jwt/JWTUtil.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

🔨 Refactor: 유효하지 않은 토큰 구분

---

build.gradle

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

💩 Chore: mariadb 연결 확인

---

src/main/java/com/backend/payring/controller/UserController.java
src/main/java/com/backend/payring/service/UserServiceImpl.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

🐛 Fix: 중복 이메일 확인 로직 수정

---

.github/workflows/develop.yml

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

🐛 Fix: 실행 명령어 수정

---

src/main/java/com/backend/payring/config/SwaggerConfig.java

어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

🔨 Refactor: Swagger JWT 설정

---

src/main/java/com/backend/payring/config/SwaggerConfig.java

closed #40  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
N/A

🐛 Fix: swagger 배포 url 변경

---

src/main/java/com/backend/payring/controller/PaymentController.java
src/main/java/com/backend/payring/controller/RoomController.java
src/main/java/com/backend/payring/controller/TransferController.java
src/main/java/com/backend/payring/dto/payment/PaymentCreateDTO.java
src/main/java/com/backend/payring/entity/RoomEntity.java
src/main/java/com/backend/payring/repository/TeamMemberRepository.java
src/main/java/com/backend/payring/repository/TransferRepository.java
src/main/java/com/backend/payring/service/PaymentService.java
src/main/java/com/backend/payring/service/PaymentServiceImpl.java
src/main/java/com/backend/payring/service/RoomService.java
src/main/java/com/backend/payring/service/RoomServiceImpl.java
src/main/java/com/backend/payring/service/TransferService.java
src/main/java/com/backend/payring/service/TransferServiceImpl.java

closed #42  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 로그인 한 유저를 @AuthenticationPrincipal 을 통해 가져오도록 변경
N/A

🔨 Refactor: 로그인 한 유저를 @AuthenticationPrincipal 을 통해 가져오도록 변경

---

src/main/java/com/backend/payring/code/ErrorCode.java
src/main/java/com/backend/payring/code/ResponseCode.java
src/main/java/com/backend/payring/controller/TransferController.java
src/main/java/com/backend/payring/service/EmailService.java
src/main/java/com/backend/payring/service/EmailServiceImpl.java
src/main/java/com/backend/payring/service/TransferService.java
src/main/java/com/backend/payring/service/TransferServiceImpl.java
src/main/resources/templates/reminder.html

closed #49  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 독촉 이메일 전송 API 작성
N/A

✨ Feature: 독촉 이메일 전송 API 작성

---

src/main/java/com/backend/payring/controller/PaymentController.java
src/main/java/com/backend/payring/converter/PaymentConverter.java
src/main/java/com/backend/payring/dto/payment/GetPaymentDTO.java
src/main/java/com/backend/payring/service/PaymentService.java
src/main/java/com/backend/payring/service/PaymentServiceImpl.java

closed #51  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용

✨ Feature: edit room list response

---

src/main/java/com/backend/payring/controller/PaymentController.java
src/main/java/com/backend/payring/converter/TransferConverter.java
src/main/java/com/backend/payring/dto/transfer/UnCompletedUserDTO.java
src/main/java/com/backend/payring/service/PaymentService.java
src/main/java/com/backend/payring/service/PaymentServiceImpl.java

closed #53  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 정산 중인 팀원 리스트 응답에 독촉 팀원 구별 가능하도록 수정
N/A

✨ Feature: 정산 중인 팀원 리스트 응답에 독촉 팀원 구별 가능하도록 수정

---

src/main/java/com/backend/payring/code/ErrorCode.java
src/main/java/com/backend/payring/code/ResponseCode.java
src/main/java/com/backend/payring/controller/RoomController.java
src/main/java/com/backend/payring/dto/room/RoomDTO.java
src/main/java/com/backend/payring/service/RoomService.java
src/main/java/com/backend/payring/service/RoomServiceImpl.java

closed #56  : 일반 개발 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 참여 중인 방 목록 전체 조회
- 특정 방 상세 정보 조회
- 특정 방 팀원 목록 조회
N/A

✨ Feature - 방 정보 조회 API 작성
